package org.summer.dp.cms.entity.base;

// Generated 2015-10-13 18:23:33 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * Dictionary generated by hbm2java
 */
@Entity
@Table(name = "dictionary")
@Cache(region="hibernate-redis", usage = CacheConcurrencyStrategy.READ_WRITE)
public class Dictionary implements java.io.Serializable {

	private static final long serialVersionUID = 6362177708108242601L;
	private Integer id;
	private String name;
	private Integer type;
	private String typeName;


	public Dictionary() {
	}

	public Dictionary(String name) {
		this.name = name;
	}

	public Dictionary(String name, Integer type) {
		this.name = name;
		this.type = type;

	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME", nullable = false, length = 64)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "TYPE", nullable = false)
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}
	
	@Column(name = "TYPE_NAME", nullable = false, length = 64)
	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	

}
