package org.summer.dp.cms.entity.base;

// Generated 2015-10-21 15:16:58 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Enterprise generated by hbm2java
 */
@Entity
@Table(name = "enterprise")
public class Enterprise implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7133986236165720027L;
	private Long id;
	private Dictionary dictionary;
	private String name;
	private String fax;
	private Integer numOfEmployee;
	private String registerAddress;
	private String emailAddress;
	private String telephone;
	private Date addDate;
	private Date modifyDate;
	private long addUserId;
	private Long modifyUserId;
	private Set<Department> departments = new HashSet<Department>(0);
	

	public Enterprise() {
	}

	public Enterprise(String name, Date addDate, long addUserId) {
		this.name = name;
		this.addDate = addDate;
		this.addUserId = addUserId;
	}

	public Enterprise(Dictionary dictionary, String name, String fax,
			Integer numOfEmployee, String registerAddress, String emailAddress,
			String telephone, Date addDate, Date modifyDate, long addUserId,
			Long modifyUserId, Set<Department> departments) {
		this.dictionary = dictionary;
		this.name = name;
		this.fax = fax;
		this.numOfEmployee = numOfEmployee;
		this.registerAddress = registerAddress;
		this.emailAddress = emailAddress;
		this.telephone = telephone;
		this.addDate = addDate;
		this.modifyDate = modifyDate;
		this.addUserId = addUserId;
		this.modifyUserId = modifyUserId;
		this.departments = departments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PROPERTY")
	public Dictionary getDictionary() {
		return this.dictionary;
	}

	public void setDictionary(Dictionary dictionary) {
		this.dictionary = dictionary;
	}

	@Column(name = "NAME", nullable = false, length = 128)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "FAX", length = 32)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "NUM_OF_EMPLOYEE")
	public Integer getNumOfEmployee() {
		return this.numOfEmployee;
	}

	public void setNumOfEmployee(Integer numOfEmployee) {
		this.numOfEmployee = numOfEmployee;
	}

	@Column(name = "REGISTER_ADDRESS", length = 128)
	public String getRegisterAddress() {
		return this.registerAddress;
	}

	public void setRegisterAddress(String registerAddress) {
		this.registerAddress = registerAddress;
	}

	@Column(name = "EMAIL_ADDRESS", length = 128)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "TELEPHONE", length = 24)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ADD_DATE", nullable = false, length = 10)
	public Date getAddDate() {
		return this.addDate;
	}

	public void setAddDate(Date addDate) {
		this.addDate = addDate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "MODIFY_DATE", length = 10)
	public Date getModifyDate() {
		return this.modifyDate;
	}

	public void setModifyDate(Date modifyDate) {
		this.modifyDate = modifyDate;
	}

	@Column(name = "ADD_USER_ID", nullable = false)
	public long getAddUserId() {
		return this.addUserId;
	}

	public void setAddUserId(long addUserId) {
		this.addUserId = addUserId;
	}

	@Column(name = "MODIFY_USER_ID")
	public Long getModifyUserId() {
		return this.modifyUserId;
	}

	public void setModifyUserId(Long modifyUserId) {
		this.modifyUserId = modifyUserId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "enterprise")
	public Set<Department> getDepartments() {
		return this.departments;
	}

	public void setDepartments(Set<Department> departments) {
		this.departments = departments;
	}

}
